# Cargo.toml
[workspace]
members = [
    "variables",
    "functions",
    "guessing_game",
    "hello_cargo",
    "branches",
    "ownership",
    "exercism/hello-world",
    "structs",
    "enums",
]
